name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: "kubernetes-sigs/aws-encryption-provider"
    - name: Docker Hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aws-encryption-provider:$(date +%F)-$(echo "${{ github.sha }}" | cut -c 1-9 )

    - name: Push Docker image
      run: docker push aws-encryption-provider:$(date +%F)-$(echo "${{GITHUB_SHA}}" | cut -c 1-9 )
